header:
  image: https://github.com/blazingdragonhk/blazingdragonhk.github.io/assets/155500927/ba487534-1ae2-48a1-a708-9e89f5f51c11
  alt: image
  width: 100
  style: "float: right; margin-left: 10px;"
title: "ç«é¾ğŸ”¥ğŸ²Blazing Dragon ğŸ˜âœŒğŸ»æ­¡è¿å¤§å®¶ğŸ˜Š"
description: "Blazing Dragonç›®æ¨™ä¿‚å¸Œæœ›å…¨éƒ¨éƒ½åšåˆ° ğŸ‡­ğŸ‡°å…¨æ¸¯æœ€å¹³+æœ€å¤šå„ªæƒ ä¿¾å¤§å®¶ é‹ªé ­åœ°é»æœƒä¿‚è¥¿ä¹é¾ğŸ²ğŸ„ğŸ’•ğŸ æ¯å€‹æ˜ŸæœŸ æˆ‘æœƒåŒå„ä½æœ‹å‹ä»”å–ºé‘½çŸ³å±±æä¸€é½Šç©æ´»å‹• å¤§å®¶æœ‰æ™‚é–“éƒ½å¯ä»¥ä¸€é½Šåƒèˆ‡â˜ºï¸ğŸ¶"
activities:
  - date: "4/1"
    name: "[2024 æ–°å¹´ç¦è¢‹ ç¬¬ä¸€å½ˆ](Event1.md)"
  - date: "6/1"
    name: "[ä¼Šè²ç¦è¢‹](Event2.md)"
  - date: "æ•¬è«‹æœŸå¾…"
    name: "[2024 æ–°å¹´ç¦è¢‹ ç¬¬äºŒå½ˆ](Event3.md)"
event_zone:
  - name: "[2024 æ–°å¹´ç¦è¢‹ ç¬¬ä¸€å½ˆ](Event1.md)"
  - name: "[6/1ä¼Šè²ç¦è¢‹](Event2.md)"
  - name: "[2024 æ–°å¹´ç¦è¢‹ ç¬¬äºŒå½ˆ](Event3.md)"
card_box_zone:
  - name: "[æ—¥ç‰ˆ](Event1.md)"
  - name: "[æ¸¯ç‰ˆ](Event1.md)"
scattered_card_zone:
  - name: "[ARå¡](Event1.md)"
  - name: "[SRå¡](Event2.md)"
  - name: "[SRå…¨åœ–äºº](Event3.md)"
  - name: "[SARå¡](Event3.md)"
  - name: "[SARå…¨åœ–äºº](Event3.md)"
table:
  - name: "[é¢äº¤/é †è±/å¹³éƒµè¡¨å–®](Google_form.md)"
